# Keep Flutter classes
-keep class io.flutter.** { *; }

# Keep Firebase classes
-keep class com.google.firebase.** { *; }

# Keep Google Play services classes
-keep class com.google.android.gms.** { *; }

# Keep annotations
-keepattributes *Annotation*

# Prevent stripping of Parcelable implementations
-keepclassmembers class * implements android.os.Parcelable {
    static ** CREATOR;
}

# Keep Google Play Core classes (used by Flutter for deferred components)
-keep class com.google.android.play.core.common.IntentSenderForResultStarter { *; }
-keep class com.google.android.play.core.tasks.** { *; }
-keep class com.google.android.play.core.splitinstall.** { *; }
-keep class com.google.android.play.core.splitcompat.** { *; }

# JNI & Native Code
-keep class com.sun.jna.** { *; }
-keep class com.google.common.reflect.** { *; }
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep classes used by App Check and other plugins
-keep class com.google.firebase.appcheck.** { *; }
-keep class io.flutter.plugins.firebase.appcheck.** { *; }

# WorkManager & Room (Fixes the WorkDatabase crash)
-keep class androidx.work.** { *; }
-keep class androidx.work.impl.WorkDatabase_Impl { *; }
-keep class androidx.room.** { *; }
-keep class * extends androidx.room.RoomDatabase
-dontwarn androidx.work.**
-dontwarn androidx.room.**

# App Startup
-keep class androidx.startup.** { *; }
-dontwarn androidx.startup.**

# Add missing rules generated by R8
-dontwarn com.google.android.play.core.**
-dontwarn com.google.firebase.crashlytics.**
-dontwarn com.google.firebase.analytics.**
-dontwarn com.google.firebase.datastorage.**
-dontwarn com.google.firebase.installations.**
-dontwarn java.lang.reflect.AnnotatedType
-dontwarn javax.annotation.**
-dontwarn com.google.common.reflect.**

# Explicitly keep Firebase Installations and DataStorage (Fixes IidStore crash)
-keep class com.google.firebase.installations.** { *; }
-keep class com.google.firebase.datastorage.** { *; }
-keep class com.google.firebase.components.** { *; }
-keep class com.google.firebase.concurrent.** { *; }

